version: '1.0.{build}-{branch}'
image: Ubuntu1804
platform: x64

cache:
- /home/appveyor/.vagrant.d/boxes

install:
- sudo wget https://download.virtualbox.org/virtualbox/5.2.22/virtualbox-5.2_5.2.22-126460~Ubuntu~bionic_amd64.deb
- sudo dpkg -i virtualbox-5.2_5.2.22-126460~Ubuntu~bionic_amd64.deb
- sudo apt-get -yq install python-pip
# How did the VirtualBox installation go?
- VBoxManage --version

# we have to download Vagrant in the install step (not init), because otherwise we´ll run into errors like
# fatal: destination path '/home/appveyor/projects/vagrant-ansible-on-appveyor' already exists and is not an empty directory.
# see https://help.appveyor.com/discussions/problems/2367-git-clone-fails-non-empty-dir
- sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.1/vagrant_2.2.1_x86_64.deb
# Install Vagrant package
- sudo dpkg -i vagrant_2.2.1_x86_64.deb
# Vagrant correctly installed?
- vagrant --version

build_script:
- vagrant up
- vagrant ssh -c "echo 'All good.'"